newsSite/urls.py
from django.contrib import admin
from django.conf import settings 
from django.urls import path, include 
from django.contrib.staticfiles.urls import static




urlpatterns = [
    path('newsapp/', include('newsapp.urls')),
    path('admin/', admin.site.urls),
 
   
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsapp/urls.py
from django.urls import path

from . import views




app_name = 'newsapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('tech', views.tech, name='tech'),
    path('art', views.art, name='art'),
    path('Sci', views.Sci, name='Sci'),
    path('business', views.business, name='business'),
    path('<int:news_id>/', views.newsdetails, name='newsdetails'),
    path('search', views.search, name='search'),
    path('subscribe', views.subscribe, name='subscribe'),
    path('subform', views.subform, name='subform'),
]
 # path('newsapp/homepage.html', views.index, name='index')
 


#app_name = 'polls'
#urlpatterns = [
   # path('', views.index, name='index'),
   # path('<int:question_id>/', views.detail, name='detail'),
   # path('<int:question_id>/results/', views.results, name='results'),
   # path('<int:question_id>/vote/', views.vote, name='vote'),
#]

newsapp/models.py
import datetime
from django.db import models
from django.utils import timezone


class News(models.Model):
    ## every news page details will contain these info
    popular = models.BooleanField(default=False)
    category = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    news_image = models.ImageField(upload_to = "images/", blank=True, null=True)
    content_short =  models.CharField(max_length=300)
    content_long = models.CharField(max_length=3000)
   
    def __str__(self):
         return self.title

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    

newsapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import News


def index(request):
    latest_news_list = News.objects.order_by('pub_date')[:2]
    popular_news_list = News.objects.filter(popular=True)[:4]
    template = loader.get_template('newsapp/homepage.html')
    context = {
       'latest_news_list': latest_news_list,
       'popular_news_list': popular_news_list,
    }
    return HttpResponse(template.render(context, request))


def tech(request):
    items= News.objects.filter(category="tech")
    template = loader.get_template('newsapp/tech.html')
    context = {
       'items': items,
    }
    return HttpResponse(template.render(context, request))

def art(request):
    items= News.objects.filter(category="art")
    template = loader.get_template('newsapp/art.html')
    context = {
       'items': items,
    }
    return HttpResponse(template.render(context, request))
    

def Sci(request):
    items= News.objects.filter(category="Sci")
    template = loader.get_template('newsapp/Sci.html')
    context = {
       'items': items,
    }
    return HttpResponse(template.render(context, request))
    

def business(request):
    items= News.objects.filter(category="business")
    template = loader.get_template('newsapp/business.html')
    context = {
       'items': items,
    }
    return HttpResponse(template.render(context, request))

def newsdetails(request, news_id):
    news = News.objects.get(pk=news_id)
    return render(request, 'newsapp/newsContent.html', {'news': news})

def search(request):        
    query =  request.GET.get('search') 
    object_list =  News.objects.filter(title__icontains=query)      
    return render(request,"newsapp/search.html", {"news":object_list})


def subscribe(request):
    return render(request,"newsapp/subscribe.html")


def subform(request):
    query =  request.GET.get('email') 
    message= "Thank you for subscribing with ABC news.\n " + "You will recieve our news each weeks!"
    return render(request,'newsapp/subscribe.html', {"message": message})
    

newsapp/templates/newsapp/Sci.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Science</title>
    <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Your description">
    <meta name="keywords" content="Your keywords">
    <meta name="author" content="Your name">
    
	{% load static %}
	<link rel="icon"  href="{% static 'newsapp/images/favicon.ico' %}" type="image/x-icon">

	<link rel="shortcut icon"  href="{% static 'newsapp/images/favicon.ico' %}"  type="image/x-icon" />

	<link rel="stylesheet"   href="{% static 'newsapp/css/bootstrap.css' %}"  type="text/css" media="screen">

	<link rel="stylesheet"  href="{% static 'newsapp/css/responsive.css' %}"   type="text/css" media="screen">

	<link rel="stylesheet"   href="{% static 'newsapp/css/camera.css' %}"  type="text/css" media="screen"> 

    <link rel="stylesheet" href="{% static 'newsapp/css/style.css' %}" type="text/css" media="screen">

		<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Bitter:400,700' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
  
</head>


<div class="bg">
<!--==============================Header=================================-->
<header>
	<div class="bg_left"></div>
    <div class="container">
    	<div class="row">
			
        	<div class="span3">
            	<div class="clearfix">
									<div class="clearfix header-block-pad">
											{% load staticfiles %}
				
										 <a href="{% url 'newsapp:index' %}"><img src="{% static 'newsapp/images/logo.jpg' %}" alt=""></a>	
									</div>
							</div>
					</div>
					
					
	
					
					<!--============================== Nav =================================-->          


			    <div class="span9" id="nav_section">
              <div class="navbar navbar_ clearfix">
                <div class="navbar-inner navbar-inner_">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse_">MENU</a>                                                   
                    <div class="nav-collapse nav-collapse_ collapse">
                        <ul class="nav sf-menu">
                          <li class="active">
                            <a href="{% url 'newsapp:index' %}">
                              Home Page
                              <span>start here</span>
                            </a>
                          </li>
                          <li >
                            <a href="{% url 'newsapp:tech'%}">
                              Technology
                            </a>
                      
                          </li>
                          <li>
                            <a href="{% url 'newsapp:Sci'%}">
                              Science
                              
                            </a>
                          </li>
                          <li>
                            <a href="{% url 'newsapp:business'%}">
                              Business
                            
                            </a>
                          </li>
                          <li>
                            <a href="{% url 'newsapp:art'%}">
                          Art
                              
                            </a>
                          </li>
                          
                        </ul>
                    </div>
                </div>
              </div>
            </div>
            
            <!--============================== End Nav =================================-->
  
      </div>   
    </div>

</header>


<!--==============================Content=================================--> 
<section id="content" style="position: relative; top:130px;" >
    <div class="container">
      
      <div class="row ">
        <div class="clearfix ">
            <h2 style="position: relative; left:50px;">Recent news </h2>
            <p style="position: relative; left:50px; top:5px;">_____________________________________________________________</p>
         
            {% if items %}

            
            <div class="span5 " >
            {% for item in items %}

            {% if forloop.counter < 3 %}
          
            {% if forloop.counter == 2 %}
            <div style="position: relative; left:95px;">
                      <img src="{{ item.news_image.url }}"  alt="" style="width: 164px; height:164px;" border="0" class="alignleft photo" />
                      <p class="max-size1">
                          <strong>{{item.title}}</strong>
                          {{item.content_short}}
                      </p> 
                      <a href="{% url 'newsapp:newsdetails' item.id %}" class="read">read more</a>
                      <div class="padcontent"></div>
                    </div>
                      </div>
                      {% else %}

                      <div >
                          <img src="{{ item.news_image.url }}"  alt="" style="width: 164px; height:164px;" border="0" class="alignleft photo" />
                          <p class="max-size1">
                              <strong>{{item.title}}</strong>
                              {{item.content_short}}
                          </p> 
                          <a href="{% url 'newsapp:newsdetails' item.id %}" class="read">read more</a>
                          <div class="padcontent"></div>
                        </div>
                          </div>


                      {% endif %}
          {% else %}
          {% if forloop.counter == 3 %}
          <div class="span6 " >
              {% endif %}
            <img src="{{ item.news_image.url }}" alt="" style="width: 164px; height:164px;"  border="0" class="alignleft photo" />
            <p class="max-size1">
                <strong>{{item.title}}</strong>
                {{item.content_short}}            </p> 
            <a href="{% url 'newsapp:newsdetails' item.id %}" class="read">read more</a>
            <div class="padcontent"></div>
          </div>
        {% endif %}

        {% endfor %}

        {% else %}
        <p>No recent news are available.</p>
    {% endif %}
       
      </div> 
    </div>
  </section>







  <div id="copyright" style="position: relative; top:140px;">
      <div class="container">
        <div class="row">	
          <div class="span9">
            
              <p>
                Copyright Hope. &copy; 2019. <a href="https://google.com">ABC NEWS</a> All rights reserved.
              </p>
    
          </div>
          <div class="span3">
              
            <!--==============================Search=========================-->
        
    
              <form id="search-form" action="{% url 'newsapp:search' %}" method="GET" accept-charset="utf-8" class="navbar-form" >
                <input type="text" name="search" value="" placeholder="Search" id="search1" >
                <a href="{% url 'newsapp:search' %}" onclick="return false" ></a>
    
              
                
              </form>
    
          </div>
        </div>
      </div>
    </div>



</div> <!-- bg -->

</body>
</html>        

newsapp/templates/newsapp/art.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Art </title>
    <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Your description">
    <meta name="keywords" content="Your keywords">
    <meta name="author" content="Your name">
    
	{% load static %}
	<link rel="icon"  href="{% static 'newsapp/images/favicon.ico' %}" type="image/x-icon">

	<link rel="shortcut icon"  href="{% static 'newsapp/images/favicon.ico' %}"  type="image/x-icon" />

	<link rel="stylesheet"   href="{% static 'newsapp/css/bootstrap.css' %}"  type="text/css" media="screen">

	<link rel="stylesheet"  href="{% static 'newsapp/css/responsive.css' %}"   type="text/css" media="screen">

	<link rel="stylesheet"   href="{% static 'newsapp/css/camera.css' %}"  type="text/css" media="screen"> 

    <link rel="stylesheet" href="{% static 'newsapp/css/style.css' %}" type="text/css" media="screen">

		<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Bitter:400,700' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
  
</head>


<div class="bg">
<!--==============================Header=================================-->
<header>
	<div class="bg_left"></div>
    <div class="container">
    	<div class="row">
			
        	<div class="span3">
            	<div class="clearfix">
									<div class="clearfix header-block-pad">
											{% load staticfiles %}
				
										 <a href="{% url 'newsapp:index' %}"><img src="{% static 'newsapp/images/logo.jpg' %}" alt=""></a>	
									</div>
							</div>
					</div>
					
					
	
					
					<!--============================== Nav =================================-->          


			    <div class="span9" id="nav_section">
              <div class="navbar navbar_ clearfix">
                <div class="navbar-inner navbar-inner_">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse_">MENU</a>                                                   
                    <div class="nav-collapse nav-collapse_ collapse">
                        <ul class="nav sf-menu">
                          <li class="active">
                            <a href="{% url 'newsapp:index' %}">
                              Home Page
                              <span>start here</span>
                            </a>
                          </li>
                          <li >
                            <a href="{% url 'newsapp:tech'%}">
                              Technology
                            </a>
                      
                          </li>
                          <li>
                            <a href="{% url 'newsapp:Sci'%}">
                              Science
                              
                            </a>
                          </li>
                          <li>
                            <a href="{% url 'newsapp:business'%}">
                              Business
                            
                            </a>
                          </li>
                          <li>
                            <a href="{% url 'newsapp:art'%}">
                          Art
                              
                            </a>
                          </li>
                          
                        </ul>
                    </div>
                </div>
              </div>
            </div>
            
            <!--============================== End Nav =================================-->
  
      </div>   
    </div>

</header>



<!--==============================Content=================================--> 
<section id="content" style="position: relative; top:130px;" >
    <div class="container">
      
      <div class="row ">
        <div class="clearfix ">
            <h2 style="position: relative; left:50px;">Recent news </h2>
            <p style="position: relative; left:50px; top:5px;">_____________________________________________________________</p>
         
            {% if items %}

            
            <div class="span5 " >
            {% for item in items %}

            {% if forloop.counter < 3 %}
          
            {% if forloop.counter == 2 %}
            <div style="position: relative; left:95px;">
                      <img src="{{ item.news_image.url }}"  alt="" style="width: 164px; height:164px;" border="0" class="alignleft photo" />
                      <p class="max-size1">
                          <strong>{{item.title}}</strong>
                          {{item.content_short}}
                      </p> 
                      <a href="{% url 'newsapp:newsdetails' item.id %}" class="read">read more</a>
                      <div class="padcontent"></div>
                    </div>
                      </div>
                      {% else %}

                      <div >
                          <img src="{{ item.news_image.url }}"  alt="" style="width: 164px; height:164px;" border="0" class="alignleft photo" />
                          <p class="max-size1">
                              <strong>{{item.title}}</strong>
                              {{item.content_short}}
                          </p> 
                          <a href="{% url 'newsapp:newsdetails' item.id %}" class="read">read more</a>
                          <div class="padcontent"></div>
                        </div>
                          </div>


                      {% endif %}
          {% else %}
          {% if forloop.counter == 3 %}
          <div class="span6 " >
              {% endif %}
            <img src="{{ item.news_image.url }}" alt="" style="width: 164px; height:164px;"  border="0" class="alignleft photo" />
            <p class="max-size1">
                <strong>{{item.title}}</strong>
                {{item.content_short}}            </p> 
            <a href="{% url 'newsapp:newsdetails' item.id %}" class="read">read more</a>
            <div class="padcontent"></div>
          </div>
        {% endif %}

        {% endfor %}

        {% else %}
        <p>No recent news are available.</p>
    {% endif %}
       
      </div> 
    </div>
  </section>




  <div id="copyright" style="position: relative; top:140px;">
      <div class="container">
        <div class="row">	
          <div class="span9">
            
              <p>
                Copyright Hope. &copy; 2019. <a href="https://google.com">ABC NEWS</a> All rights reserved.
              </p>
    
          </div>
          <div class="span3">
              
            <!--==============================Search=========================-->
        
    
              <form id="search-form" action="{% url 'newsapp:search' %}" method="GET" accept-charset="utf-8" class="navbar-form" >
                <input type="text" name="search" value="" placeholder="Search" id="search1" >
                <a href="{% url 'newsapp:search' %}" onclick="return false" ></a>
    
              
                
              </form>
    
          </div>
        </div>
      </div>
    </div>





</div> <!-- bg -->

</body>
</html>        

newsapp/templates/newsapp/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
    <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Your description">
    <meta name="keywords" content="Your keywords">
	<meta name="author" content="Your name">
	
	{% load static %}
	<link rel="icon"  href="{% static 'newsapp/images/favicon.ico' %}" type="image/x-icon">

	<link rel="shortcut icon"  href="{% static 'newsapp/images/favicon.ico' %}"  type="image/x-icon" />

	<link rel="stylesheet"   href="{% static 'newsapp/css/bootstrap.css' %}"  type="text/css" media="screen">

	<link rel="stylesheet"  href="{% static 'newsapp/css/responsive.css' %}"   type="text/css" media="screen">

	<link rel="stylesheet"   href="{% static 'newsapp/css/camera.css' %}"  type="text/css" media="screen"> 

    <link rel="stylesheet" href="{% static 'newsapp/css/style.css' %}" type="text/css" media="screen">

		<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Bitter:400,700' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
		
		<style>
				.seacrhicon {
					background-image: url("/static/newsapp/images/search.png");
				
				}
				</style>

</head>

<body>

<div class="bg">
<!--==============================Header=================================-->
<header>
	<div class="bg_left"></div>
    <div class="container">
    	<div class="row">
			
        	<div class="span3">
            	<div class="clearfix">
									<div class="clearfix header-block-pad">
											{% load staticfiles %}
				
										 <a href="{% url 'newsapp:index' %}"><img src="{% static 'newsapp/images/logo.jpg' %}" alt=""></a>					
									</div>
							</div>
					</div>
					
					
					<!--============================== Nav =================================-->          


			    <div class="span9" id="nav_section">
			      <div class="navbar navbar_ clearfix">
			        <div class="navbar-inner navbar-inner_">
			            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse_">MENU</a>                                                   
			            <div class="nav-collapse nav-collapse_ collapse">
			                <ul class="nav sf-menu">
			                  <li class="active">
													<a href="{% url 'newsapp:index' %}">
														Home Page
														<span>start here</span>
													</a>
												</li>
												<li >
													<a href="{% url 'newsapp:tech'%}">
														Technology
													</a>
										
												</li>
												<li>
													<a href="{% url 'newsapp:Sci'%}">
														Science
														
													</a>
												</li>
												<li>
													<a href="{% url 'newsapp:business'%}">
														Business
													
													</a>
												</li>
												<li>
													<a href="{% url 'newsapp:art'%}">
												Art
														
													</a>
												</li>
												
			                </ul>
			            </div>
			        </div>
			      </div>
			    </div>
					
					<!--============================== End Nav =================================-->

      </div>   
    </div>

</header>


<!--==============================Content=================================--> 
<section id="content" style="position: relative; top:130px;" >
  <div class="container">
	
    <div class="row ">
	  <div class="clearfix ">
    	<div class="span3 ">
          <h1>Welcome  to ABC NEWS</h1>
					
					<p>
						<b>
							Suspendisse enim arcu, convallis non, cursus sed, dignissim et, est. Aenean semper aliquet libero.
						</b>
						In ante velit, cursus ut, ultrices vitae, tempor ut, risus. Duis pulvinar. Vestibulum vel pede at sapien sodales mattis. Quisque pretium, lacus nec iaculis vehicula, arcu libero consectetuer massa, auctor aliquet mauris ligula id ipsum. Vestibulum pede. Maecenas sit amet augue. Sed blandit lectus eget lectus. Mauris justo. Curabitur nibh lectus, dapibus id, tempor eu, tempor non, erat. 
					</p>
					
					<div class="padcontent"></div>
			</div>
		
    	<div class="span6 ">
          <h2>Recent news </h2>
          {% if latest_news_list %}

			{% for item in latest_news_list %}
		
			
          	<img  style="width: 164px; height:164px;" src= "{{ item.news_image.url }}"  alt=""  border="0" class="alignleft photo" />
					<p class="max-size1">
						<strong>{{item.title}}</strong>
						{{item.content_short}}
					</p> 
					<a href="{% url 'newsapp:newsdetails' item.id %}" class="read">read more</a>
					<div class="padcontent"></div>

            {% endfor %}
            </ul>
        {% else %}
            <p>No recent news are available.</p>
        {% endif %}

					
        </div>
		
    	<div class="span3 ">
          <h2>Mission</h2>
					<ul class="list">
						<li>MISSION / VISION</li>
						<li>HISTORY</li>
						<li>STAFF</li>
					
					</ul>
					<div class="padcontent"></div>
					{% load static %}
					
					<img src="{% static 'newsapp/images/bg_donate.jpg' %}" alt="" width="108" height="143" border="0" class="alignright latin" />
					<h3>Subscribe now to get the latest world news!</h3>
					<a href="{% url 'newsapp:subscribe' %}" class="donate">Subscribe</a>
					<div class="padcontent"></div>
      </div>
	  </div>
    </div> 
  </div>
</section>

<!--==============================banners=================================--> 


<section id="banners" style="position: relative; top:110px;">
  <div class="container">
    <div class="row ">
			<div class="clearfix ">
				
					<h2 style="position: relative; left:50px;" >Popular This Year</h2>
					{% if popular_news_list %}

					{% for item in popular_news_list %}


					{% if forloop.counter == 1 %}

				<div class="span3 banner_1">
						{% endif %}


			{% if forloop.counter == 2 %}

				<div class="span3 banner_2">
						{% endif %}

								
			{% if forloop.counter == 3%}

			<div class="span3 banner_3">
						{% endif %}

										
				{% if forloop.counter == 4 %}

				<div class="span3 banner_4">
				{% endif %}
						

				  <img style="width: 270px; height:200px;" src="{{ item.news_image.url }}" alt=""  border="0" />
					<h4>{{item.title}}</h4>
					<p>
							{{item.content_short}}
					</p>
					<a href="{% url 'newsapp:newsdetails' item.id %}" class="more">read more</a>
        </div>
		
		{% endfor %}
				
		{% else %}
        <p>No recent news are available.</p>
    {% endif %}
				
				
			</div>
    </div> 
  </div>
</section>
   


<div id="copyright" style="position: relative; top:140px;">
	<div class="container">
		<div class="row">	
			<div class="span9">
				
					<p>
						Copyright Hope. &copy; 2019. <a href="https://google.com">ABC NEWS</a> All rights reserved.
					</p>

			</div>
			<div class="span3">
					
				<!--==============================Search=========================-->
		

					<form id="search-form" action="{% url 'newsapp:search' %}" method="GET" accept-charset="utf-8" class="navbar-form" >
						<input type="text" name="search" value="" placeholder="Search" id="search1" >
						<a href="{% url 'newsapp:search' %}" onclick="return false" ></a>

					
						
					</form>

			</div>
		</div>
	</div>
</div>




</div> <!-- bg -->


</body>
</html>